global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          application: 'university-monitoring-app'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
        labels:
          database: 'monitoring_db'

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
