apiVersion: v1
kind: Service
metadata:
  name: journal-frontend
  labels:
    app: journal
    layer: frontend
spec:
  selector:
    app: journal
    layer: frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
