services:
  app:
    build: .
    container_name: monitoring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitoring_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: 12201
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      graylog:
        condition: service_started
    networks:
      - monitoring-network

  postgres:
    image: postgres:16
    container_name: monitoring-postgres
    environment:
      POSTGRES_DB: monitoring_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    container_name: monitoring-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres123@postgres:5432/monitoring_db?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring-network
    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer:5.4.0
    container_name: monitoring-adminer
    ports:
      - "8081:8080"
    networks:
      - monitoring-network
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:12.3.0-18329792253
    container_name: monitoring-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring-network
    depends_on:
      - prometheus

  graylog:
    image: graylog/graylog:5.2
    container_name: monitoring-graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper123456789012345678901234567890123456789012345678901234567890123456789012"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514"
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - monitoring-network
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:7
    container_name: monitoring-mongodb
    environment:
      MONGO_INITDB_DATABASE: graylog
    volumes:
      - mongodb_data:/data/db
    networks:
      - monitoring-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: monitoring-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitoring-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: monitoring-zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix123
    ports:
      - "10051:10051"
    networks:
      - monitoring-network
    depends_on:
      - zabbix-postgres

  zabbix-postgres:
    image: postgres:16
    container_name: monitoring-zabbix-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix123
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: monitoring-zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix123
      PHP_TZ: Europe/Moscow
    ports:
      - "8082:8080"
    networks:
      - monitoring-network
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: monitoring-zabbix-agent
    environment:
      ZBX_HOSTNAME: "monitoring-app"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_PASSIVE_ALLOW: "true"
      ZBX_ACTIVE_ALLOW: "true"
    ports:
      - "10050:10050"
    networks:
      - monitoring-network
    depends_on:
      - zabbix-server
      - app

networks:
  monitoring-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  mongodb_data:
  elasticsearch_data:
  graylog_data:
  zabbix_postgres_data:
